apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - oadp-namespace.yaml
  - oadp-operatorgroup.yaml
  - oadp-subscription.yaml
#  - oadp-cloud-credentials-secret.yaml
#  - oadp-velero.yaml
  
