apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: infrastructure
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
  source:
    path: infrastructure/infrastructure-application
    repoURL: ''
