apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oadp
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: "https://kubernetes.default.svc"
  project: infrastructure
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
  source:
    path: infrastructure/localstorageoperator
    repoURL: 'https://github.com/tkagn/ocp4gitops-public'
